### ISSUE TITLE
Problems when running dtopotools_examples.ipynb locally

### ISSUE THREAD

**Issue by svater** [clawpack/apps#60]
I tried to run the dtopotools_examples notebook locally with clawpack 5.3.1 and ran into some problems:

`from clawpack.geoclaw.util import get_remote_file` results in an error stating that get_remote_file cannot be imported. This function does not exist in clawpack.geoclaw.util. Instead I could use `from clawpack.clawutil.data import get_remote_file`.

Under the heading "Create a fault using the NOAA SIFT database directly" the file info_sz.dat.txt is supposed to be loaded by the command `f2 = dtopotools.SiftFault(sift_slips)`. The file is supposed to be in the dirrectory '/usr/lib64/python2.7/site-packages/clawpack/geoclaw/data/info_sz.dat.txt'. However, it seems that this file is not installed during the installation of clawpack, although it is in the source directory.

I hope that helps.

Best regards, Stefan

**Comment by mandli** [comment]
Thanks @svater, this notebook has not been updated in a while as you probably had guessed and has fallen a bit behind development.  The first is easy any you found.  The second is a bit more puzzling but probably has to do with the way Python installs data files, it may have skipped that one so we will have to take a look at what is going on there.

**Comment by svater** [comment]
You are welcome :-) Yes, I guessed that this was the case. Since I observed these errors, I thought you might be interested in... Hope, you are well.

**Comment by rjleveque** [comment]
I think these have been resolved in recent releases.
