### ISSUE TITLE
Access rights for multilayer-examples

### ISSUE THREAD

**Issue by Dirivian** [clawpack/apps#84]
Cloning the apps repository using --recursive was not successful for multilayer examples. Also, the surge-examples folder cloned is empty.

Trying again with git submodule init did not resolve it either.

![multi](https://user-images.githubusercontent.com/25760009/27887418-8024821c-6195-11e7-8978-5ec351165d4e.png)

**Comment by mandli** [comment]
It looks like an ssh-key problem rather than a permissions problem.  Have you tried going into the offending directories and doing a `git checkout master`?

**Comment by Dirivian** [comment]
It displays that I am up-to-date with master.

![multi](https://user-images.githubusercontent.com/25760009/27934695-bab12c7a-625b-11e7-89b4-c3019b377d55.png)

**Comment by mandli** [comment]
Did you do `git submodule init` in the `$CLAW/apps` directory?

BTW, regardless of our success here I think the `--recursive` thing is wrong so we need to change that.

**Comment by Dirivian** [comment]
`git submodule init` did not work initially but a bit googling revealed that it could either be a folder permission problem or my ssh key was not set up correctly and submodules couldn't be cloned using HTTPS. 

I added a new ssh key and `git submodule init` works perfectly.

**Comment by mandli** [comment]
@Dirivian I kind of think we should document what the process that works is so that others do not have the same issues that you ran into.  Would you mind doing a PR to the apps repository that explains what needs to be done to checkout the multilayer and storm surge submodules?

**Comment by mandli** [comment]
I am going to close this as we figured out a way around it and if someone has a similar issue we can refer to this.
